### ISSUE TITLE
Csci 3260 midterm

### ISSUE THREAD

**Issue by wongtszchiu** [yuchitoto/CUHK-CSCI-2017-2021-Course-Source-Repository#9]
Please share the past midterm paper, thanks.

**Comment by yuchitoto** [comment]
@sinyiwsy

**Comment by wongtszchiu** [comment]
@sinyiwsy help!

**Comment by sinyiwsy** [comment]
> @sinyiwsy help!

Uploaded. Please check.

**Comment by wongtszchiu** [comment]
@sinyiwsy Thank you very much, btw do you have the answer of it?

**Comment by sinyiwsy** [comment]
> @sinyiwsy Thank you very much, btw do you have the answer of it?

I don't have. But you can ask me the question if you don't know how to do.

**Comment by wongtszchiu** [comment]
@sinyiwsy omg, you are awesome.
